"""Repo inspection and file rendering for the `init` skill (design doc §14 "Init skill";
implementation plan Step 11). Deterministic, unit-testable glue; the interactive knob-registry
walk itself (asking the user, composing rationale text) lives in `skills/init/SKILL.md`'s prose
and is not this module's job.

Inspection is reused, not reimplemented, from building blocks the rest of the plugin already has:
`lib.checks.detect_checks` for build/test/static commands, `lib.ticketing.github.is_github_remote`
for whether the repo's `origin` is GitHub-hosted. `inspect_repo` never proposes a value it can't
trace back to concrete repo evidence -- a knob with no signal here stays at its built-in default,
walked (not proposed) by the skill itself.

    inspect_repo(repo_root) -> dict                                    # evidence-backed proposals
    render_pipeline_yaml(customized, rationales, schema_version) -> str  # -> .agents/pipeline.yaml text
    parse_schema_version(pipeline_yaml_text) -> str | None               # read the header back
    diff_against_existing(existing, proposed) -> dict                   # added/changed/removed
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Any

import yaml

from lib.checks import detect_checks
from lib.ticketing.github import is_github_remote

_SCHEMA_VERSION_RE = re.compile(r"^#\s*schema_version:\s*(\S+)\s*$", re.MULTILINE)


def _origin_remote_url(repo_root: str | Path) -> str | None:
    # `git config --get`, not `git remote get-url` -- the latter applies any local
    # `url.<base>.insteadOf` rewrite (e.g. a corporate git proxy), which would make "is this repo
    # GitHub-hosted" reflect the local rewrite target instead of the remote the project actually
    # declares.
    result = subprocess.run(
        ["git", "config", "--get", "remote.origin.url"],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def inspect_repo(repo_root: str | Path) -> dict[str, Any]:
    """Evidence-backed proposals only, shaped like a partial `pipeline.yaml`: a `checks` block
    when the repo's Makefile defines at least one recognized target (design doc: "for this repo
    it would propose bazel build/test, clang-format, clang-tidy" -- `fixtures/sample-project`'s
    own Makefile is this build's stand-in target), and `ticketing.system: github_issues` when
    `origin` is GitHub-hosted. Absent keys are not "no opinion" placeholders -- the init skill's
    registry walk shows the built-in default for anything missing here, exactly as if inspection
    had never run."""
    proposals: dict[str, Any] = {}

    detected = detect_checks(repo_root)
    checks = {key: value for key, value in detected.items() if value is not None}
    if checks:
        proposals["checks"] = checks

    if is_github_remote(_origin_remote_url(repo_root)):
        proposals["ticketing"] = {"system": "github_issues"}

    return proposals


def render_pipeline_yaml(customized: dict[str, Any], rationales: dict[str, str], schema_version: str) -> str:
    """Render `.agents/pipeline.yaml` text: a header noting the schema version this file targets
    (read back by `parse_schema_version` on a later `/pipeline:init` re-run, design doc §14
    "Idempotent re-runs"), then one block per customized top-level knob with its rationale as a
    leading comment. `customized` is expected to already be schema-valid -- this function only
    renders, it does not validate. Keys left at the built-in default must simply not be passed in
    (design doc §14: "omit keys left at default so defaults can evolve without stale copies")."""
    lines = [
        "# Generated by /pipeline:init -- do not hand-edit the schema_version line.",
        f"# schema_version: {schema_version}",
    ]
    for key, value in customized.items():
        lines.append("")
        rationale = rationales.get(key)
        if rationale:
            lines.append(f"# {rationale}")
        block = yaml.safe_dump({key: value}, sort_keys=False, default_flow_style=False)
        lines.append(block.rstrip("\n"))
    return "\n".join(lines).rstrip("\n") + "\n"


def parse_schema_version(pipeline_yaml_text: str) -> str | None:
    """The `schema_version` a previous `/pipeline:init` run wrote into the file's header comment,
    or None for a file `/pipeline:init` never generated (e.g. hand-written) -- treated the same as
    "no version on record" rather than an error, so a re-run still proceeds, just without a
    version to migrate from."""
    match = _SCHEMA_VERSION_RE.search(pipeline_yaml_text)
    return match.group(1) if match else None


def diff_against_existing(existing: dict[str, Any], proposed: dict[str, Any]) -> dict[str, Any]:
    """Top-level-knob diff between an existing `pipeline.yaml`'s data and this run's proposal,
    surfaced to the user on a re-run (design doc §14 "Idempotent re-runs... propose a diff").
    Granularity is the whole top-level knob (e.g. all of `checks`), not each nested sub-key --
    enough for the user to decide whether to accept the new proposal, without re-deriving
    `lib.resolve_config`'s own dotted-path provenance machinery for what is just a display diff."""
    added = {key: value for key, value in proposed.items() if key not in existing}
    removed = {key: value for key, value in existing.items() if key not in proposed}
    changed = {
        key: {"from": existing[key], "to": proposed[key]}
        for key in proposed
        if key in existing and existing[key] != proposed[key]
    }
    return {"added": added, "removed": removed, "changed": changed}


def _cli(argv: list[str] | None = None) -> int:
    import json
    import sys

    argv = sys.argv[1:] if argv is None else argv
    repo_root = argv[0] if argv else "."
    print(json.dumps(inspect_repo(repo_root)))
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli())
